### ISSUE TITLE
Requires additional libraries

### ISSUE THREAD

**Issue by thomassisson** [fenixk19/pcmanfm-image-size-module#1]
As well as basic build essentials, building requires libmagick-dev or some variation of ImageMagick development libraries.

[You can move this to the README, and delete this issue.]

Also, libtool is installed on my system, but it wants the binary. The binary is in libtool-bin on Debian based systems (current version is Ubuntu 16.04.

**Comment by thomassisson** [comment]
I give up. Google can't make love. Stop.

**Comment by fenixk19** [comment]
Thanks for your interest!

I just verified the build process on Ubuntu 16.04.

It requires at least the following packages:

```
sudo apt-get install libtool-bin libmagickcore-dev libfm-dev
```

Also, since the Magick-config binary has been moved outside the $PATH, make should be issued the following way:

```
PATH="/usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16:$PATH" make
```

This way the plugin compiles well for the Ubuntu 16.04.

However, there is also an issue with running `sudo make install`. My Makefile tries to install the plugin to the path `/usr/lib/libfm/pcmanfm-image-size-plugin.so`. The modules path has been replaced with `/usr/lib/x86_64-linux-gnu/libfm/modules/` on Ubuntu 16.04. So consider doing manual install by issuing

```
sudo cp .libs/pcmanfm-image-size-plugin.so /usr/lib/x86_64-linux-gnu/libfm/modules/
```

After following this steps, I see that the plugin works fine on Ubuntu 16.04.

I'm not sure how to update the Makefile in a way it is compatible with Ubuntu 16.04 and other operating systems at the same time. Perhaps that will require introduction of some autoconf tools or something. I'm not quite interested in maintaining a complex build system for this small module currently. I'll update the README with the dependencies information. Feel free to submit PRs on the build scripts in case you know how to improve it.
